---
    AWSTemplateFormatVersion: "2010-09-09"
    Resources:
      S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
          Tags:
            - Key: organization-id
              Value: demo-value